[package]
name = "rqbe"
version = "0.1.0"
edition = "2024"

[dependencies]
bitvec = "1.1.1"
paste = "1.0.15"
target-lexicon = { version = "0.13.5", features = ["std"] }
idset = "0.5.0"
object = { version = "0.40.0", features = [ "elf", "write", "build"] }
thiserror = "2.0.20"

[lib]
name = "librqbe"
path = "src/lib.rs"

[[bin]]
name = "rqbe"
path = "src/bin.rs"
