[package]
name = "rqbe"
version = "0.1.0"
edition = "2024"

[dependencies]
bitvec = "1.1.1"
paste = "1.0.15"
target-lexicon = { version = "0.13.5", features = ["std"] }
winnow = { version = "1.0.4", features = ["simd"] }
idset = "0.2.0"

[lib]
name = "librqbe"
path = "src/lib.rs"

[[bin]]
name = "rqbe"
path = "src/bin.rs"
